model_list:
  # RUN POD VLLM Models
  - model_name: runpod-vllm-mistral
    litellm_params:
      model: hosted_vllm/mistralai/Mistral-7B-Instruct-v0.3
      api_base: https://gnfzhaynntlve2-8080.proxy.runpod.net/v1
      api_key: none
  # OPENAI Models
  - model_name: oai-gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: <OPENAI_API_KEY>
  - model_name: oai-text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: <OPENAI_API_KEY>
  # Anthropic Models
  - model_name: anthropic-claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: <ANTROPIC_API_KEY>
  # Ollama Models
  - model_name: ollama-mistral
    litellm_params:
      model: ollama/mistral
      api_base: http://192.168.2.114:11434
      api_key: none
  - model_name: ollama-llama-vision
    litellm_params:
      model: ollama/llama3.2-vision
      api_base: http://192.168.2.114:11434
      api_key: none
